[workspace]

members = [
    "eruptrace_pure",
    "eruptrace_scene",
]

[package]
name = "eruptrace-rs"
version = "0.1.0"
authors = ["Adam Gąsior"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eruptrace_pure = { path = "eruptrace_pure" }
eruptrace_scene = { path = "eruptrace_scene" }

nalgebra-glm = "0.16"
pico-args = "0.4"
