[package]
name = "eruptrace_deferred"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

eruptrace_scene = { path = "../eruptrace_scene" }
eruptrace_vk = { path = "../eruptrace_vk" }

erupt = { git = "https://gitlab.com/Adanos020/erupt" }
vk-mem-3-erupt = { git = "https://github.com/Adanos020/vk-mem-3-erupt" }
std140 = "0.2"

itertools = "0.13"

nalgebra-glm = "0.19"
